# Stage 1: Build
FROM node:20-alpine AS build
WORKDIR /app
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
# Copy các file config từ my-project vào WORKDIR /app
COPY my-project/package*.json ./
RUN npm install

# Copy toàn bộ nội dung trong my-project vào /app
COPY my-project/ .

# Chạy build -> tạo ra folder /app/dist
RUN npm run build

# Stage 2: Serve
FROM nginx:stable-alpine

# Copy từ stage build, folder dist sang folder mặc định của nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Chú ý: nginx.conf nằm ngoài my-project nên copy trực tiếp
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]